package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoryInfo generated by hbm2java
 */
@Entity
@Table(name = "category_info", catalog = "charter")
public class CategoryInfo implements java.io.Serializable {

	private long categoryId;
	private String sellerinfoId;
	private String categoryName;
	private String categoryDetail;
	private byte[] categoryImage;

	public CategoryInfo() {
	}

	public CategoryInfo(long categoryId) {
		this.categoryId = categoryId;
	}

	public CategoryInfo(long categoryId, String sellerinfoId,
			String categoryName, String categoryDetail, byte[] categoryImage) {
		this.categoryId = categoryId;
		this.sellerinfoId = sellerinfoId;
		this.categoryName = categoryName;
		this.categoryDetail = categoryDetail;
		this.categoryImage = categoryImage;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "sellerinfo_id", length = 45)
	public String getSellerinfoId() {
		return this.sellerinfoId;
	}

	public void setSellerinfoId(String sellerinfoId) {
		this.sellerinfoId = sellerinfoId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "category_detail", length = 45)
	public String getCategoryDetail() {
		return this.categoryDetail;
	}

	public void setCategoryDetail(String categoryDetail) {
		this.categoryDetail = categoryDetail;
	}

	@Column(name = "category_image")
	public byte[] getCategoryImage() {
		return this.categoryImage;
	}

	public void setCategoryImage(byte[] categoryImage) {
		this.categoryImage = categoryImage;
	}

}
