package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 7:18:27 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerRental generated by hbm2java
 */
@Entity
@Table(name = "customer_rental", catalog = "charter")
public class CustomerRental implements java.io.Serializable {

	private long customerRetalId;
	private Long customerId;
	private String rentalStatusCode;
	private Date rentalDateIut;
	private Date rentalReturnDate;
	private Long subcategoryId;
	private Integer rentalAmountDue;
	private String otherDetails;

	public CustomerRental() {
	}

	public CustomerRental(long customerRetalId) {
		this.customerRetalId = customerRetalId;
	}

	public CustomerRental(long customerRetalId, Long customerId,
			String rentalStatusCode, Date rentalDateIut, Date rentalReturnDate,
			Long subcategoryId, Integer rentalAmountDue, String otherDetails) {
		this.customerRetalId = customerRetalId;
		this.customerId = customerId;
		this.rentalStatusCode = rentalStatusCode;
		this.rentalDateIut = rentalDateIut;
		this.rentalReturnDate = rentalReturnDate;
		this.subcategoryId = subcategoryId;
		this.rentalAmountDue = rentalAmountDue;
		this.otherDetails = otherDetails;
	}

	@Id
	@Column(name = "customer_retal_id", unique = true, nullable = false)
	public long getCustomerRetalId() {
		return this.customerRetalId;
	}

	public void setCustomerRetalId(long customerRetalId) {
		this.customerRetalId = customerRetalId;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "rental_status_code", length = 45)
	public String getRentalStatusCode() {
		return this.rentalStatusCode;
	}

	public void setRentalStatusCode(String rentalStatusCode) {
		this.rentalStatusCode = rentalStatusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rental_date_iut", length = 19)
	public Date getRentalDateIut() {
		return this.rentalDateIut;
	}

	public void setRentalDateIut(Date rentalDateIut) {
		this.rentalDateIut = rentalDateIut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rental_return_date", length = 19)
	public Date getRentalReturnDate() {
		return this.rentalReturnDate;
	}

	public void setRentalReturnDate(Date rentalReturnDate) {
		this.rentalReturnDate = rentalReturnDate;
	}

	@Column(name = "subcategory_id")
	public Long getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(Long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

	@Column(name = "rental_amount_due")
	public Integer getRentalAmountDue() {
		return this.rentalAmountDue;
	}

	public void setRentalAmountDue(Integer rentalAmountDue) {
		this.rentalAmountDue = rentalAmountDue;
	}

	@Column(name = "other_details", length = 450)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
