package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerInfo generated by hbm2java
 */
@Entity
@Table(name = "customer_info", catalog = "charter")
public class CustomerInfo implements java.io.Serializable {

	private long customerId;
	private String customerFname;
	private String customerEmail;
	private String customerLocation;
	private String customerImage;
	private String customerAge;
	private String customerPhone;
	private String customerLname;

	public CustomerInfo() {
	}

	public CustomerInfo(long customerId) {
		this.customerId = customerId;
	}

	public CustomerInfo(long customerId, String customerFname,
			String customerEmail, String customerLocation,
			String customerImage, String customerAge, String customerPhone,
			String customerLname) {
		this.customerId = customerId;
		this.customerFname = customerFname;
		this.customerEmail = customerEmail;
		this.customerLocation = customerLocation;
		this.customerImage = customerImage;
		this.customerAge = customerAge;
		this.customerPhone = customerPhone;
		this.customerLname = customerLname;
	}

	@Id
	@Column(name = "customer_id", unique = true, nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_fname", length = 45)
	public String getCustomerFname() {
		return this.customerFname;
	}

	public void setCustomerFname(String customerFname) {
		this.customerFname = customerFname;
	}

	@Column(name = "customer_email", length = 45)
	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	@Column(name = "customer_location", length = 45)
	public String getCustomerLocation() {
		return this.customerLocation;
	}

	public void setCustomerLocation(String customerLocation) {
		this.customerLocation = customerLocation;
	}

	@Column(name = "customer_image", length = 45)
	public String getCustomerImage() {
		return this.customerImage;
	}

	public void setCustomerImage(String customerImage) {
		this.customerImage = customerImage;
	}

	@Column(name = "customer_age", length = 45)
	public String getCustomerAge() {
		return this.customerAge;
	}

	public void setCustomerAge(String customerAge) {
		this.customerAge = customerAge;
	}

	@Column(name = "customer_phone", length = 45)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "customer_lname", length = 45)
	public String getCustomerLname() {
		return this.customerLname;
	}

	public void setCustomerLname(String customerLname) {
		this.customerLname = customerLname;
	}

}
