package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "charter")
public class Feedback implements java.io.Serializable {

	private long feedbackId;
	private String feedbackDesc;
	private Long customerId;
	private Long sellerId;
	private Long subcategoryId;

	public Feedback() {
	}

	public Feedback(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	public Feedback(long feedbackId, String feedbackDesc, Long customerId,
			Long sellerId, Long subcategoryId) {
		this.feedbackId = feedbackId;
		this.feedbackDesc = feedbackDesc;
		this.customerId = customerId;
		this.sellerId = sellerId;
		this.subcategoryId = subcategoryId;
	}

	@Id
	@Column(name = "Feedback_id", unique = true, nullable = false)
	public long getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	@Column(name = "Feedback_desc", length = 450)
	public String getFeedbackDesc() {
		return this.feedbackDesc;
	}

	public void setFeedbackDesc(String feedbackDesc) {
		this.feedbackDesc = feedbackDesc;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "seller_id")
	public Long getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Long sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "subcategory_id")
	public Long getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(Long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

}
