package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "charter")
public class Orders implements java.io.Serializable {

	private long orderId;
	private long customerId;
	private long ordernumber;
	private long paymentId;
	private Date orderDate;
	private Date shipDate;
	private Long shipId;
	private String orderAmount;
	private String orderTrackingnumber;
	private Long orderTax;
	private String orderShipaddress1;
	private String orderShipaddress2;
	private String orderCity;
	private String orderState;
	private String orderZip;
	private Date orderPaymentDate;

	public Orders() {
	}

	public Orders(long orderId, long customerId, long ordernumber,
			long paymentId) {
		this.orderId = orderId;
		this.customerId = customerId;
		this.ordernumber = ordernumber;
		this.paymentId = paymentId;
	}

	public Orders(long orderId, long customerId, long ordernumber,
			long paymentId, Date orderDate, Date shipDate, Long shipId,
			String orderAmount, String orderTrackingnumber, Long orderTax,
			String orderShipaddress1, String orderShipaddress2,
			String orderCity, String orderState, String orderZip,
			Date orderPaymentDate) {
		this.orderId = orderId;
		this.customerId = customerId;
		this.ordernumber = ordernumber;
		this.paymentId = paymentId;
		this.orderDate = orderDate;
		this.shipDate = shipDate;
		this.shipId = shipId;
		this.orderAmount = orderAmount;
		this.orderTrackingnumber = orderTrackingnumber;
		this.orderTax = orderTax;
		this.orderShipaddress1 = orderShipaddress1;
		this.orderShipaddress2 = orderShipaddress2;
		this.orderCity = orderCity;
		this.orderState = orderState;
		this.orderZip = orderZip;
		this.orderPaymentDate = orderPaymentDate;
	}

	@Id
	@Column(name = "Order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "customer_id", nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Ordernumber", nullable = false)
	public long getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(long ordernumber) {
		this.ordernumber = ordernumber;
	}

	@Column(name = "Payment_id", nullable = false)
	public long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(long paymentId) {
		this.paymentId = paymentId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Order_date", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Ship_date", length = 19)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "Ship_Id")
	public Long getShipId() {
		return this.shipId;
	}

	public void setShipId(Long shipId) {
		this.shipId = shipId;
	}

	@Column(name = "Order_amount", length = 45)
	public String getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(String orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Column(name = "Order_trackingnumber", length = 45)
	public String getOrderTrackingnumber() {
		return this.orderTrackingnumber;
	}

	public void setOrderTrackingnumber(String orderTrackingnumber) {
		this.orderTrackingnumber = orderTrackingnumber;
	}

	@Column(name = "Order_Tax")
	public Long getOrderTax() {
		return this.orderTax;
	}

	public void setOrderTax(Long orderTax) {
		this.orderTax = orderTax;
	}

	@Column(name = "Order_Shipaddress1", length = 45)
	public String getOrderShipaddress1() {
		return this.orderShipaddress1;
	}

	public void setOrderShipaddress1(String orderShipaddress1) {
		this.orderShipaddress1 = orderShipaddress1;
	}

	@Column(name = "Order_shipaddress2", length = 45)
	public String getOrderShipaddress2() {
		return this.orderShipaddress2;
	}

	public void setOrderShipaddress2(String orderShipaddress2) {
		this.orderShipaddress2 = orderShipaddress2;
	}

	@Column(name = "Order_city", length = 45)
	public String getOrderCity() {
		return this.orderCity;
	}

	public void setOrderCity(String orderCity) {
		this.orderCity = orderCity;
	}

	@Column(name = "Order_state", length = 45)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "Order_Zip", length = 45)
	public String getOrderZip() {
		return this.orderZip;
	}

	public void setOrderZip(String orderZip) {
		this.orderZip = orderZip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Order_payment_Date", length = 19)
	public Date getOrderPaymentDate() {
		return this.orderPaymentDate;
	}

	public void setOrderPaymentDate(Date orderPaymentDate) {
		this.orderPaymentDate = orderPaymentDate;
	}

}
