package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "charter")
public class Payment implements java.io.Serializable {

	private long paymentId;
	private String paymentType;
	private String allowed;
	private Long customerId;

	public Payment() {
	}

	public Payment(long paymentId) {
		this.paymentId = paymentId;
	}

	public Payment(long paymentId, String paymentType, String allowed,
			Long customerId) {
		this.paymentId = paymentId;
		this.paymentType = paymentType;
		this.allowed = allowed;
		this.customerId = customerId;
	}

	@Id
	@Column(name = "paymentId", unique = true, nullable = false)
	public long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(long paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "payment_type", length = 45)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "allowed", length = 11)
	public String getAllowed() {
		return this.allowed;
	}

	public void setAllowed(String allowed) {
		this.allowed = allowed;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

}
