package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SellerInfo generated by hbm2java
 */
@Entity
@Table(name = "seller_info", catalog = "charter")
public class SellerInfo implements java.io.Serializable {

	private long sellerId;
	private String sellerType;
	private String sellerEmail;
	private String sellerPhone;
	private String sellerReview;
	private String sellerFeedback;
	private Long sellerProductId;
	private String sellerLocation;
	private String sellerAddress;

	public SellerInfo() {
	}

	public SellerInfo(long sellerId) {
		this.sellerId = sellerId;
	}

	public SellerInfo(long sellerId, String sellerType, String sellerEmail,
			String sellerPhone, String sellerReview, String sellerFeedback,
			Long sellerProductId, String sellerLocation, String sellerAddress) {
		this.sellerId = sellerId;
		this.sellerType = sellerType;
		this.sellerEmail = sellerEmail;
		this.sellerPhone = sellerPhone;
		this.sellerReview = sellerReview;
		this.sellerFeedback = sellerFeedback;
		this.sellerProductId = sellerProductId;
		this.sellerLocation = sellerLocation;
		this.sellerAddress = sellerAddress;
	}

	@Id
	@Column(name = "seller_id", unique = true, nullable = false)
	public long getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(long sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "seller_type", length = 45)
	public String getSellerType() {
		return this.sellerType;
	}

	public void setSellerType(String sellerType) {
		this.sellerType = sellerType;
	}

	@Column(name = "seller_email", length = 45)
	public String getSellerEmail() {
		return this.sellerEmail;
	}

	public void setSellerEmail(String sellerEmail) {
		this.sellerEmail = sellerEmail;
	}

	@Column(name = "seller_phone", length = 45)
	public String getSellerPhone() {
		return this.sellerPhone;
	}

	public void setSellerPhone(String sellerPhone) {
		this.sellerPhone = sellerPhone;
	}

	@Column(name = "seller_review", length = 250)
	public String getSellerReview() {
		return this.sellerReview;
	}

	public void setSellerReview(String sellerReview) {
		this.sellerReview = sellerReview;
	}

	@Column(name = "seller_feedback", length = 250)
	public String getSellerFeedback() {
		return this.sellerFeedback;
	}

	public void setSellerFeedback(String sellerFeedback) {
		this.sellerFeedback = sellerFeedback;
	}

	@Column(name = "seller_product_id")
	public Long getSellerProductId() {
		return this.sellerProductId;
	}

	public void setSellerProductId(Long sellerProductId) {
		this.sellerProductId = sellerProductId;
	}

	@Column(name = "seller_location", length = 45)
	public String getSellerLocation() {
		return this.sellerLocation;
	}

	public void setSellerLocation(String sellerLocation) {
		this.sellerLocation = sellerLocation;
	}

	@Column(name = "seller_address", length = 45)
	public String getSellerAddress() {
		return this.sellerAddress;
	}

	public void setSellerAddress(String sellerAddress) {
		this.sellerAddress = sellerAddress;
	}

}
