package com.learnlogic.system.rental.model;

// Generated Jul 11, 2015 5:51:02 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubcategoryInfo generated by hbm2java
 */
@Entity
@Table(name = "subcategory_info", catalog = "charter")
public class SubcategoryInfo implements java.io.Serializable {

	private long subcategoryId;
	private Long categoryId;
	private Long sellerId;
	private String subcategoryName;
	private String subcategoryDesc;
	private String subcategoryImage;
	private Integer subcategoryItemPrice;

	public SubcategoryInfo() {
	}

	public SubcategoryInfo(long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

	public SubcategoryInfo(long subcategoryId, Long categoryId, Long sellerId,
			String subcategoryName, String subcategoryDesc,
			String subcategoryImage, Integer subcategoryItemPrice) {
		this.subcategoryId = subcategoryId;
		this.categoryId = categoryId;
		this.sellerId = sellerId;
		this.subcategoryName = subcategoryName;
		this.subcategoryDesc = subcategoryDesc;
		this.subcategoryImage = subcategoryImage;
		this.subcategoryItemPrice = subcategoryItemPrice;
	}

	@Id
	@Column(name = "subcategory_id", unique = true, nullable = false)
	public long getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

	@Column(name = "category_id")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "seller_id")
	public Long getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(Long sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "subcategory_name", length = 45)
	public String getSubcategoryName() {
		return this.subcategoryName;
	}

	public void setSubcategoryName(String subcategoryName) {
		this.subcategoryName = subcategoryName;
	}

	@Column(name = "subcategory_desc", length = 450)
	public String getSubcategoryDesc() {
		return this.subcategoryDesc;
	}

	public void setSubcategoryDesc(String subcategoryDesc) {
		this.subcategoryDesc = subcategoryDesc;
	}

	@Column(name = "subcategory_image", length = 45)
	public String getSubcategoryImage() {
		return this.subcategoryImage;
	}

	public void setSubcategoryImage(String subcategoryImage) {
		this.subcategoryImage = subcategoryImage;
	}

	@Column(name = "subcategory_item_price")
	public Integer getSubcategoryItemPrice() {
		return this.subcategoryItemPrice;
	}

	public void setSubcategoryItemPrice(Integer subcategoryItemPrice) {
		this.subcategoryItemPrice = subcategoryItemPrice;
	}

}
